#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_Play
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CinemaPlayBD")]
	public partial class FilmsLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertФильмы(Фильмы instance);
    partial void UpdateФильмы(Фильмы instance);
    partial void DeleteФильмы(Фильмы instance);
    #endregion
		
		public FilmsLinqDataContext() : 
				base(global::Cinema_Play.Properties.Settings.Default.CinemaPlayBDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FilmsLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FilmsLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FilmsLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FilmsLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Фильмы> Фильмы
		{
			get
			{
				return this.GetTable<Фильмы>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Фильмы")]
	public partial class Фильмы : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Название_фильма;
		
		private string _Производство_компанией;
		
		private System.Nullable<System.DateTime> _Год_выпуска;
		
		private string _Жанр;
		
		private string _Длительность;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnНазвание_фильмаChanging(string value);
    partial void OnНазвание_фильмаChanged();
    partial void OnПроизводство_компаниейChanging(string value);
    partial void OnПроизводство_компаниейChanged();
    partial void OnГод_выпускаChanging(System.Nullable<System.DateTime> value);
    partial void OnГод_выпускаChanged();
    partial void OnЖанрChanging(string value);
    partial void OnЖанрChanged();
    partial void OnДлительностьChanging(string value);
    partial void OnДлительностьChanged();
    #endregion
		
		public Фильмы()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Название фильма]", Storage="_Название_фильма", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Название_фильма
		{
			get
			{
				return this._Название_фильма;
			}
			set
			{
				if ((this._Название_фильма != value))
				{
					this.OnНазвание_фильмаChanging(value);
					this.SendPropertyChanging();
					this._Название_фильма = value;
					this.SendPropertyChanged("Название_фильма");
					this.OnНазвание_фильмаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Производство компанией]", Storage="_Производство_компанией", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Производство_компанией
		{
			get
			{
				return this._Производство_компанией;
			}
			set
			{
				if ((this._Производство_компанией != value))
				{
					this.OnПроизводство_компаниейChanging(value);
					this.SendPropertyChanging();
					this._Производство_компанией = value;
					this.SendPropertyChanged("Производство_компанией");
					this.OnПроизводство_компаниейChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Год выпуска]", Storage="_Год_выпуска", DbType="Date")]
		public System.Nullable<System.DateTime> Год_выпуска
		{
			get
			{
				return this._Год_выпуска;
			}
			set
			{
				if ((this._Год_выпуска != value))
				{
					this.OnГод_выпускаChanging(value);
					this.SendPropertyChanging();
					this._Год_выпуска = value;
					this.SendPropertyChanged("Год_выпуска");
					this.OnГод_выпускаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Жанр", DbType="NVarChar(50)")]
		public string Жанр
		{
			get
			{
				return this._Жанр;
			}
			set
			{
				if ((this._Жанр != value))
				{
					this.OnЖанрChanging(value);
					this.SendPropertyChanging();
					this._Жанр = value;
					this.SendPropertyChanged("Жанр");
					this.OnЖанрChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Длительность", DbType="NChar(50)")]
		public string Длительность
		{
			get
			{
				return this._Длительность;
			}
			set
			{
				if ((this._Длительность != value))
				{
					this.OnДлительностьChanging(value);
					this.SendPropertyChanging();
					this._Длительность = value;
					this.SendPropertyChanged("Длительность");
					this.OnДлительностьChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
