#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_Play
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CinemaPlayBD")]
	public partial class SeansiLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertСеансы(Сеансы instance);
    partial void UpdateСеансы(Сеансы instance);
    partial void DeleteСеансы(Сеансы instance);
    #endregion
		
		public SeansiLinqDataContext() : 
				base(global::Cinema_Play.Properties.Settings.Default.CinemaPlayBDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SeansiLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SeansiLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SeansiLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SeansiLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Сеансы> Сеансы
		{
			get
			{
				return this.GetTable<Сеансы>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Сеансы")]
	public partial class Сеансы : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Код_сеанса;
		
		private string _Фильм;
		
		private string _Цена;
		
		private System.Nullable<System.DateTime> _Дата;
		
		private string _Время;
		
		private int _Зал;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnКод_сеансаChanging(int value);
    partial void OnКод_сеансаChanged();
    partial void OnФильмChanging(string value);
    partial void OnФильмChanged();
    partial void OnЦенаChanging(string value);
    partial void OnЦенаChanged();
    partial void OnДатаChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаChanged();
    partial void OnВремяChanging(string value);
    partial void OnВремяChanged();
    partial void OnЗалChanging(int value);
    partial void OnЗалChanged();
    #endregion
		
		public Сеансы()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Код сеанса]", Storage="_Код_сеанса", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Код_сеанса
		{
			get
			{
				return this._Код_сеанса;
			}
			set
			{
				if ((this._Код_сеанса != value))
				{
					this.OnКод_сеансаChanging(value);
					this.SendPropertyChanging();
					this._Код_сеанса = value;
					this.SendPropertyChanged("Код_сеанса");
					this.OnКод_сеансаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Фильм", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Фильм
		{
			get
			{
				return this._Фильм;
			}
			set
			{
				if ((this._Фильм != value))
				{
					this.OnФильмChanging(value);
					this.SendPropertyChanging();
					this._Фильм = value;
					this.SendPropertyChanged("Фильм");
					this.OnФильмChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Цена", DbType="NChar(50)")]
		public string Цена
		{
			get
			{
				return this._Цена;
			}
			set
			{
				if ((this._Цена != value))
				{
					this.OnЦенаChanging(value);
					this.SendPropertyChanging();
					this._Цена = value;
					this.SendPropertyChanged("Цена");
					this.OnЦенаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Дата", DbType="Date")]
		public System.Nullable<System.DateTime> Дата
		{
			get
			{
				return this._Дата;
			}
			set
			{
				if ((this._Дата != value))
				{
					this.OnДатаChanging(value);
					this.SendPropertyChanging();
					this._Дата = value;
					this.SendPropertyChanged("Дата");
					this.OnДатаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Время", DbType="NChar(50)")]
		public string Время
		{
			get
			{
				return this._Время;
			}
			set
			{
				if ((this._Время != value))
				{
					this.OnВремяChanging(value);
					this.SendPropertyChanging();
					this._Время = value;
					this.SendPropertyChanged("Время");
					this.OnВремяChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Зал", DbType="Int NOT NULL")]
		public int Зал
		{
			get
			{
				return this._Зал;
			}
			set
			{
				if ((this._Зал != value))
				{
					this.OnЗалChanging(value);
					this.SendPropertyChanging();
					this._Зал = value;
					this.SendPropertyChanged("Зал");
					this.OnЗалChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
